# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aioketraapi
from aioketraapi.api.group_operations_api import GroupOperationsApi  # noqa: E501
from aioketraapi.rest import ApiException


class TestGroupOperationsApi(unittest.TestCase):
    """GroupOperationsApi unit test stubs"""

    def setUp(self):
        self.api = aioketraapi.api.group_operations_api.GroupOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_get(self):
        """Test case for groups_get

        Gets the list of groups  # noqa: E501
        """
        pass

    def test_groups_group_id_get(self):
        """Test case for groups_group_id_get

        Gets a single group object  # noqa: E501
        """
        pass

    def test_groups_group_id_state_get(self):
        """Test case for groups_group_id_state_get

        Gets the state of a single lamp group  # noqa: E501
        """
        pass

    def test_groups_group_id_state_put(self):
        """Test case for groups_group_id_state_put

        Sets the state of a single lamp group  # noqa: E501
        """
        pass

    def test_groups_state_post(self):
        """Test case for groups_state_post

        Sets the state of a lamp group  # noqa: E501
        """
        pass

    def test_root_get(self):
        """Test case for root_get

        Get keypads and groups  (and scenes in API schema 4 or later)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
