# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aioketraapi
from aioketraapi.models.lamp_state import LampState  # noqa: E501
from aioketraapi.rest import ApiException


class TestLampState(unittest.TestCase):
    """LampState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLampState(self):
        """Test LampState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aioketraapi.models.lamp_state.LampState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
