# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aioketraapi
from aioketraapi.models.inline_response2004_content import InlineResponse2004Content  # noqa: E501
from aioketraapi.rest import ApiException


class TestInlineResponse2004Content(unittest.TestCase):
    """InlineResponse2004Content unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2004Content(self):
        """Test InlineResponse2004Content"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aioketraapi.models.inline_response2004_content.InlineResponse2004Content()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
