# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aioketraapi
from aioketraapi.endpoints.hub_operations_api import HubOperationsApi  # noqa: E501
from aioketraapi.rest import ApiException


class TestHubOperationsApi(unittest.TestCase):
    """HubOperationsApi unit test stubs"""

    def setUp(self):
        self.api = HubOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hub_get(self):
        """Test case for hub_get

        Gets properties of the hub  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
