# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aioketraapi
from aioketraapi.models.keypad import Keypad  # noqa: E501
from aioketraapi.rest import ApiException


class TestKeypad(unittest.TestCase):
    """Keypad unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeypad(self):
        """Test Keypad"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aioketraapi.models.keypad.Keypad()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
