# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aioketraapi
from aioketraapi.models.inline_response20012 import InlineResponse20012  # noqa: E501
from aioketraapi.rest import ApiException


class TestInlineResponse20012(unittest.TestCase):
    """InlineResponse20012 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20012(self):
        """Test InlineResponse20012"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aioketraapi.models.inline_response20012.InlineResponse20012()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
