# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import aioketraapi
from aioketraapi.models.inline_response200_content import InlineResponse200Content  # noqa: E501
from aioketraapi.rest import ApiException


class TestInlineResponse200Content(unittest.TestCase):
    """InlineResponse200Content unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200Content(self):
        """Test InlineResponse200Content"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aioketraapi.models.inline_response200_content.InlineResponse200Content()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
