# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from aioketraapi.configuration import Configuration


class ButtonChangeNotification(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'button_id': 'str',
        'client_id': 'str',
        'level': 'int',
        'activated': 'bool',
        'time_utc': 'datetime'
    }

    attribute_map = {
        'button_id': 'button_id',
        'client_id': 'client_id',
        'level': 'level',
        'activated': 'activated',
        'time_utc': 'time_utc'
    }

    def __init__(self, button_id=None, client_id=None, level=None, activated=None, time_utc=None, local_vars_configuration=None):  # noqa: E501
        """ButtonChangeNotification - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._button_id = None
        self._client_id = None
        self._level = None
        self._activated = None
        self._time_utc = None
        self.discriminator = None

        if button_id is not None:
            self.button_id = button_id
        if client_id is not None:
            self.client_id = client_id
        if level is not None:
            self.level = level
        if activated is not None:
            self.activated = activated
        if time_utc is not None:
            self.time_utc = time_utc

    @property
    def button_id(self):
        """Gets the button_id of this ButtonChangeNotification.  # noqa: E501


        :return: The button_id of this ButtonChangeNotification.  # noqa: E501
        :rtype: str
        """
        return self._button_id

    @button_id.setter
    def button_id(self, button_id):
        """Sets the button_id of this ButtonChangeNotification.


        :param button_id: The button_id of this ButtonChangeNotification.  # noqa: E501
        :type button_id: str
        """

        self._button_id = button_id

    @property
    def client_id(self):
        """Gets the client_id of this ButtonChangeNotification.  # noqa: E501


        :return: The client_id of this ButtonChangeNotification.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this ButtonChangeNotification.


        :param client_id: The client_id of this ButtonChangeNotification.  # noqa: E501
        :type client_id: str
        """

        self._client_id = client_id

    @property
    def level(self):
        """Gets the level of this ButtonChangeNotification.  # noqa: E501


        :return: The level of this ButtonChangeNotification.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this ButtonChangeNotification.


        :param level: The level of this ButtonChangeNotification.  # noqa: E501
        :type level: int
        """

        self._level = level

    @property
    def activated(self):
        """Gets the activated of this ButtonChangeNotification.  # noqa: E501


        :return: The activated of this ButtonChangeNotification.  # noqa: E501
        :rtype: bool
        """
        return self._activated

    @activated.setter
    def activated(self, activated):
        """Sets the activated of this ButtonChangeNotification.


        :param activated: The activated of this ButtonChangeNotification.  # noqa: E501
        :type activated: bool
        """

        self._activated = activated

    @property
    def time_utc(self):
        """Gets the time_utc of this ButtonChangeNotification.  # noqa: E501

        time of notification  # noqa: E501

        :return: The time_utc of this ButtonChangeNotification.  # noqa: E501
        :rtype: datetime
        """
        return self._time_utc

    @time_utc.setter
    def time_utc(self, time_utc):
        """Sets the time_utc of this ButtonChangeNotification.

        time of notification  # noqa: E501

        :param time_utc: The time_utc of this ButtonChangeNotification.  # noqa: E501
        :type time_utc: datetime
        """

        self._time_utc = time_utc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ButtonChangeNotification):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ButtonChangeNotification):
            return True

        return self.to_dict() != other.to_dict()
