# coding: utf-8

"""
    Ketra Lighting API

    Control your Ketra lights  # noqa: E501

    OpenAPI spec version: 1.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200Content(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'keypads': 'list[Keypad]',
        'groups': 'list[Group]',
        'scenes': 'list[Scene]'
    }

    attribute_map = {
        'keypads': 'Keypads',
        'groups': 'Groups',
        'scenes': 'Scenes'
    }

    def __init__(self, keypads=None, groups=None, scenes=None):  # noqa: E501
        """InlineResponse200Content - a model defined in Swagger"""  # noqa: E501
        self._keypads = None
        self._groups = None
        self._scenes = None
        self.discriminator = None
        if keypads is not None:
            self.keypads = keypads
        if groups is not None:
            self.groups = groups
        if scenes is not None:
            self.scenes = scenes

    @property
    def keypads(self):
        """Gets the keypads of this InlineResponse200Content.  # noqa: E501


        :return: The keypads of this InlineResponse200Content.  # noqa: E501
        :rtype: list[Keypad]
        """
        return self._keypads

    @keypads.setter
    def keypads(self, keypads):
        """Sets the keypads of this InlineResponse200Content.


        :param keypads: The keypads of this InlineResponse200Content.  # noqa: E501
        :type: list[Keypad]
        """

        self._keypads = keypads

    @property
    def groups(self):
        """Gets the groups of this InlineResponse200Content.  # noqa: E501


        :return: The groups of this InlineResponse200Content.  # noqa: E501
        :rtype: list[Group]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this InlineResponse200Content.


        :param groups: The groups of this InlineResponse200Content.  # noqa: E501
        :type: list[Group]
        """

        self._groups = groups

    @property
    def scenes(self):
        """Gets the scenes of this InlineResponse200Content.  # noqa: E501


        :return: The scenes of this InlineResponse200Content.  # noqa: E501
        :rtype: list[Scene]
        """
        return self._scenes

    @scenes.setter
    def scenes(self, scenes):
        """Sets the scenes of this InlineResponse200Content.


        :param scenes: The scenes of this InlineResponse200Content.  # noqa: E501
        :type: list[Scene]
        """

        self._scenes = scenes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200Content, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200Content):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
